#` see SMG.md for documentation

library(R6)

AbstractDataset <- R6Class("AbstractDataset", list(
  name = NA,
  publication_metadata = NA,
  case_modifier = NA,
  generation_time = NA,
  incubation_period = NA,
  reporting_delay = NA,
  region_scale = NA,
  truncation = NA,
  stable = TRUE,
  target_folder = NA,
  summary_dir = NA,
  data_args = NULL,
  initialize = function(
    name,
    publication_metadata,
    region_scale,
    case_modifier = NA,
    generation_time = NA,
    incubation_period = NA,
    reporting_delay = NA,
    stable = TRUE,
    data_args = NULL,
    truncation = 3
  ) {
    self$name <- name
    self$publication_metadata <- publication_metadata
    self$case_modifier <- case_modifier
    self$generation_time <- generation_time
    self$incubation_period <- incubation_period
    self$reporting_delay <- reporting_delay
    self$stable <- stable
    self$data_args <- data_args
    self$region_scale <- region_scale
    self$truncation <- truncation
  }
))
# This seemed a better name than global...
SuperRegion <- R6Class("SuperRegion",
                       inherit = AbstractDataset,
                       public = list(covid_national_data_identifier = "ecdc",
                                     initialize = function(...,
                                                           covid_national_data_identifier = "ecdc",
                                                           region_scale = "Country",
                                                           folder_name = NA) {
                                       super$initialize(..., region_scale)
                                       self$covid_national_data_identifier <- covid_national_data_identifier
                                       highest_folder <- ifelse(region_scale == "Country", "national/", "region/")
                                       middle_folder <- ifelse(is.na(folder_name), self$name, folder_name)
                                       tail_target_folder <- ifelse(region_scale == "Country", "/national", "/region")
                                       self$target_folder <- paste0(highest_folder, middle_folder, tail_target_folder)
                                       self$summary_dir <- paste0(highest_folder, middle_folder, "/summary")
                                     }))

Region <- R6Class("Region",
                  inherit = AbstractDataset,
                  public = list(covid_regional_data_identifier = NA,
                                cases_subregion_source = "region_level_1",
                                data_args = NULL,
                                initialize = function(...,
                                                      covid_regional_data_identifier = NA,
                                                      cases_subregion_source = "region_level_1",
                                                      region_scale = "Region",
                                                      folder_name = NA,
                                                      dataset_folder_name = "cases") {

                                  super$initialize(..., region_scale)
                                  self$covid_regional_data_identifier <- covid_regional_data_identifier
                                  self$cases_subregion_source <- cases_subregion_source
                                  middle_folder <- ifelse(is.na(folder_name), self$name, folder_name)
                                  self$target_folder <- paste0("subnational/", middle_folder, "/", dataset_folder_name, "/national")
                                  self$summary_dir <- paste0("subnational/", middle_folder, "/", dataset_folder_name, "/summary")
                                }))

PublicationMetadata <- R6Class("PublicationMetadata",
                               public = list(
                                 title = "",
                                 description = "",
                                 breakdown_unit = "",
                                 country = NA,
                                 initialize = function(title,
                                                       description, breakdown_unit, country = NA) {
                                   self$title <- title
                                   self$description <- description
                                   if (breakdown_unit %in% c("continent", "country", "region", "state")) {
                                     self$breakdown_unit <- breakdown_unit
                                   }else {
                                     stop("invalid breakdown unit")
                                   }
                                   if (is.na(country)) {
                                     if (breakdown_unit %in% c("region", "state")) {
                                       stop("country must be specified if breakdown is below country level (region / state)")
                                     }
                                   }else {
                                     if (!country %in% DATAVERSE_COUNTRIES) {
                                       stop("Invalid country - ", country, " - must be one of ", DATAVERSE_COUNTRIES)
                                     }
                                   }
                                   self$country <- country
                                 }
                               ))

DATAVERSE_COUNTRIES <- c(
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia, Plurinational State of",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and Mcdonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, the Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela, Bolivarian Republic of",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands")